following_grid_category:
  type: list
  list_type: category
  default: ""
  description: "list_of_category_slugs_or_ids"

vote_button_text:
  default: "Theo dõi"
  description: "text_for_unvoted_state"
  type: string

voted_button_text:
  default: "Đang theo dõi"
  description: "text_for_voted_state"
  type: string
