following_grid_category:
  type: list
  list_type: category
  default: ""
  description: "following_grid.settings.category_description"

vote_button_text:
  default: "Theo dõi"
  description: "following_grid.settings.vote_text_label"
  type: string

voted_button_text:
  default: "Đang theo dõi"
  description: "following_grid.settings.voted_text_label"
  type: string

enable_bulk_select:
  default: true
  description: "following_grid.settings.enable_bulk_label"
  type: bool

bulk_select_max_items:
  default: 0
  description: "following_grid.settings.max_items_label"
  type: integer
